spring:
  profiles:
    active: local
  application:
    name: Coronavirus API
  jackson:
    default-property-inclusion: non_null

server:
  port: 8080

logging.level.*: INFO

---
spring:
  profiles: local
  data:
    mongodb:
      uri: mongodb://localhost:27017/coronaDB
      database: coronavirusDB